import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>E commerce app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <p className="text-[hsl(280,100%,70%)]">E commerce</p> App
          </h1>
          <div className="flex gap-4">
            <Link href="/login">
              <button className="max-w-xs rounded-lg bg-white/10 p-4 text-white hover:bg-white/20">
                Log In
              </button>
            </Link>
            <Link href="/signup">
              <button className="max-w-xs rounded-lg bg-white/10 p-4 text-white hover:bg-white/20">
                Sign Up
              </button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
